<?php
/**
 * Central bilingual dictionary. Add new UI/document strings here once and
 * they become available in both languages everywhere via t('key', $lang).
 */

$GLOBALS['LANG'] = [
    'en' => [
        // App chrome
        'app_name' => 'QVESYS Quotation',
        'dashboard' => 'Dashboard',
        'quotations' => 'Quotations',
        'clients' => 'Clients',
        'company' => 'Company',
        'items' => 'Items & Rates',
        'settings' => 'Settings',
        'logout' => 'Log out',
        'new_quotation' => 'New Quotation',
        'search' => 'Search',
        'save' => 'Save',
        'save_draft' => 'Save Draft',
        'cancel' => 'Cancel',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'view' => 'View',
        'print' => 'Print / Save PDF',
        'duplicate' => 'Duplicate',
        'add' => 'Add',
        'actions' => 'Actions',
        'status' => 'Status',
        'total_quotations' => 'Total Quotations',
        'total_value' => 'Total Value',
        'accepted' => 'Accepted',
        'pending' => 'Pending',
        'draft' => 'Draft',
        'sent' => 'Sent',
        'rejected' => 'Rejected',
        'expired' => 'Expired',
        'recent_quotations' => 'Recent Quotations',
        'welcome' => 'Welcome back',
        'login' => 'Log in',
        'username' => 'Username',
        'password' => 'Password',
        'login_title' => 'Sign in to your workspace',
        'login_error' => 'Incorrect username or password.',

        // Quotation editor
        'client' => 'Client',
        'select_client' => 'Select a client',
        'select_company' => 'Select a company',
        'new_client' => '+ Add new client',
        'quotation_no' => 'Quotation No.',
        'date' => 'Date',
        'valid_until' => 'Valid Until',
        'template_style' => 'Template Style',
        'language' => 'Language',
        'item_description' => 'Item / Description',
        'hsn_sac' => 'HSN/SAC',
        'qty' => 'Qty',
        'unit' => 'Unit',
        'rate' => 'Rate',
        'discount' => 'Discount %',
        'tax' => 'GST %',
        'amount' => 'Amount',
        'add_item' => 'Add Item',
        'add_from_catalog' => 'Add from catalog',
        'subtotal' => 'Subtotal',
        'total_discount' => 'Total Discount',
        'taxable_amount' => 'Taxable Amount',
        'cgst' => 'CGST',
        'sgst' => 'SGST',
        'igst' => 'IGST',
        'round_off' => 'Round Off',
        'grand_total' => 'Grand Total',
        'in_words' => 'Amount in Words',
        'notes' => 'Notes',
        'subject' => 'Subject',
        'terms' => 'Terms & Conditions',
        'bank_details' => 'Bank Details',
        'authorized_signatory' => 'Authorized Signatory',
        'for' => 'For',
        'thank_you' => 'Thank you for your business!',
        'this_is_computer_generated' => 'This is a computer-generated quotation and does not require a physical signature.',
        'prepared_by' => 'Prepared by',
        'gstin' => 'GSTIN',
        'pan' => 'PAN',
        'phone' => 'Phone',
        'email' => 'Email',
        'address' => 'Address',
        'to' => 'To',
        'from' => 'From',
        'quotation' => 'Quotation',
        'proforma_invoice' => 'Proforma Invoice',
        'estimate' => 'Estimate',
        'validity_note' => 'This quotation is valid until',
        'sno' => 'S.No',

        // Clients / Items pages
        'client_name' => 'Client / Company Name',
        'contact_person' => 'Contact Person',
        'state' => 'State',
        'state_code' => 'State Code',
        'item_name' => 'Item Name',
        'no_records' => 'No records yet.',
        'confirm_delete' => 'Are you sure you want to delete this?',

        // Import / Export
        'import' => 'Import',
        'export' => 'Export',
        'export_excel' => 'Excel',
        'export_word' => 'Word',
        'export_pdf' => 'PDF',
        'sample_format' => 'Sample Import Format',
        'download_sample' => 'Download sample file',
        'choose_csv' => 'Choose a CSV file',
        'import_hint' => 'Match the columns to the sample format below, then click Import.',
        'imported_count' => 'records imported successfully.',
        'import_skipped' => 'records skipped (missing name).',
        'import_failed' => 'Import failed. Please check the file format.',

        // Settings
        'company_profile' => 'Company Profile',
        'company_name' => 'Company Name',
        'tagline' => 'Tagline',
        'logo' => 'Logo',
        'quotation_settings' => 'Quotation Settings',
        'number_prefix' => 'Number Prefix',
        'next_number' => 'Next Number',
        'default_validity' => 'Default Validity (days)',
        'default_terms' => 'Default Terms & Conditions',
        'change_password' => 'Change Password',
        'current_password' => 'Current Password',
        'new_password' => 'New Password',
        'saved_successfully' => 'Saved successfully.',
        'bill_customization' => 'Quotaion Customization',
        'enable_header' => 'Enable Header Branding',
        'enable_footer' => 'Enable Footer Section',
        'font_style' => 'Font Style',
        'font_size' => 'Font Size',
        'theme_preset' => 'Theme Preset',
        'theme_color' => 'Primary Color',
        'accent_color' => 'Accent Color',
        'preset_classic' => 'Classic Navy',
        'preset_dark' => 'Sleek Charcoal',
        'preset_green' => 'Forest Green',
        'preset_purple' => 'Royal Purple',
        'preset_red' => 'Crimson Red',
        'preset_custom' => 'Custom Color',
        'comparative_quotation' => 'New Comparative Quotation',
        'comparative_quotations' => 'Comparative Quotations',
        'option_group' => 'Option Group',
        'companies' => 'Companies',
        'add_company' => 'Add Company',
        'back_to_list' => 'Back to List',
    ],
    'ta' => [
        'app_name' => 'QVESYS மேற்கோள்',
        'dashboard' => 'டாஷ்போர்டு',
        'quotations' => 'மேற்கோள்கள்',
        'clients' => 'வாடிக்கையாளர்கள்',
        'company' => 'நிறுவனம்',
        'items' => 'பொருட்கள் & விலை',
        'settings' => 'அமைப்புகள்',
        'logout' => 'வெளியேறு',
        'new_quotation' => 'புதிய மேற்கோள்',
        'search' => 'தேடு',
        'save' => 'சேமி',
        'save_draft' => 'வரைவு சேமி',
        'cancel' => 'ரத்து செய்',
        'edit' => 'திருத்து',
        'delete' => 'நீக்கு',
        'view' => 'பார்',
        'print' => 'அச்சிடு / PDF சேமி',
        'duplicate' => 'நகல் எடு',
        'add' => 'சேர்',
        'actions' => 'செயல்கள்',
        'status' => 'நிலை',
        'total_quotations' => 'மொத்த மேற்கோள்கள்',
        'total_value' => 'மொத்த மதிப்பு',
        'accepted' => 'ஏற்கப்பட்டது',
        'pending' => 'நிலுவையில்',
        'draft' => 'வரைவு',
        'sent' => 'அனுப்பப்பட்டது',
        'rejected' => 'நிராகரிக்கப்பட்டது',
        'expired' => 'காலாவதியானது',
        'recent_quotations' => 'சமீபத்திய மேற்கோள்கள்',
        'welcome' => 'மீண்டும் வருக',
        'login' => 'உள்நுழை',
        'username' => 'பயனர் பெயர்',
        'password' => 'கடவுச்சொல்',
        'login_title' => 'உங்கள் பணியிடத்தில் நுழையவும்',
        'login_error' => 'பயனர் பெயர் அல்லது கடவுச்சொல் தவறு.',

        'client' => 'வாடிக்கையாளர்',
        'select_client' => 'வாடிக்கையாளரைத் தேர்ந்தெடுக்கவும்',
        'select_company' => 'நிறுவனத்தைத் தேர்ந்தெடுக்கவும்',
        'new_client' => '+ புதிய வாடிக்கையாளர் சேர்',
        'quotation_no' => 'மேற்கோள் எண்',
        'date' => 'தேதி',
        'valid_until' => 'செல்லுபடியாகும் தேதி',
        'template_style' => 'வடிவமைப்பு பாணி',
        'language' => 'மொழி',
        'item_description' => 'பொருள் / விவரம்',
        'hsn_sac' => 'HSN/SAC',
        'qty' => 'எண்ணிக்கை',
        'unit' => 'அளவு',
        'rate' => 'விலை',
        'discount' => 'தள்ளுபடி %',
        'tax' => 'GST %',
        'amount' => 'தொகை',
        'add_item' => 'பொருள் சேர்',
        'add_from_catalog' => 'பட்டியலிலிருந்து சேர்',
        'subtotal' => 'உபமொத்தம்',
        'total_discount' => 'மொத்த தள்ளுபடி',
        'taxable_amount' => 'வரி விதிக்கத்தக்க தொகை',
        'cgst' => 'CGST',
        'sgst' => 'SGST',
        'igst' => 'IGST',
        'round_off' => 'ரவுண்ட் ஆஃப்',
        'grand_total' => 'மொத்த தொகை',
        'in_words' => 'தொகை (எழுத்தில்)',
        'notes' => 'குறிப்புகள்',
        'subject' => 'பொருள்',
        'terms' => 'விதிமுறைகள் & நிபந்தனைகள்',
        'bank_details' => 'வங்கி விவரங்கள்',
        'authorized_signatory' => 'அங்கீகரிக்கப்பட்ட கையொப்பம்',
        'for' => 'சார்பாக',
        'thank_you' => 'உங்கள் வணிகத்திற்கு நன்றி!',
        'this_is_computer_generated' => 'இது கணினி உருவாக்கிய மேற்கோள்; கையொப்பம் தேவையில்லை.',
        'prepared_by' => 'தயாரித்தவர்',
        'gstin' => 'ஜிஎஸ்டிஐஎன்',
        'pan' => 'பான்',
        'phone' => 'தொலைபேசி',
        'email' => 'மின்னஞ்சல்',
        'address' => 'முகவரி',
        'to' => 'பெறுநர்',
        'from' => 'அனுப்புநர்',
        'quotation' => 'மேற்கோள்',
        'proforma_invoice' => 'ப்ரோஃபார்மா விலைப்பட்டியல்',
        'estimate' => 'மதிப்பீடு',
        'validity_note' => 'இந்த மேற்கோள் இந்த தேதி வரை செல்லுபடியாகும்',
        'sno' => 'வ.எண்',

        'client_name' => 'வாடிக்கையாளர் / நிறுவனப் பெயர்',
        'contact_person' => 'தொடர்பு நபர்',
        'state' => 'மாநிலம்',
        'state_code' => 'மாநில குறியீடு',
        'item_name' => 'பொருளின் பெயர்',
        'no_records' => 'இதுவரை பதிவுகள் இல்லை.',
        'confirm_delete' => 'இதை நீக்க வேண்டுமா?',

        'import' => 'இறக்குமதி',
        'export' => 'ஏற்றுமதி',
        'export_excel' => 'Excel',
        'export_word' => 'Word',
        'export_pdf' => 'PDF',
        'sample_format' => 'மாதிரி இறக்குமதி வடிவம்',
        'download_sample' => 'மாதிரி கோப்பைப் பதிவிறக்கவும்',
        'choose_csv' => 'ஒரு CSV கோப்பைத் தேர்ந்தெடுக்கவும்',
        'import_hint' => 'கீழே உள்ள மாதிரி வடிவத்திற்கு ஏற்ப நெடுவரிசைகளைப் பொருத்தி, பிறகு இறக்குமதி செய்யவும்.',
        'imported_count' => 'பதிவுகள் வெற்றிகரமாக இறக்குமதி செய்யப்பட்டன.',
        'import_skipped' => 'பதிவுகள் தவிர்க்கப்பட்டன (பெயர் இல்லை).',
        'import_failed' => 'இறக்குமதி தோல்வியடைந்தது. கோப்பு வடிவத்தைச் சரிபார்க்கவும்.',

        'company_profile' => 'நிறுவன விவரம்',
        'company_name' => 'நிறுவனப் பெயர்',
        'tagline' => 'வாசகம்',
        'logo' => 'லோகோ',
        'quotation_settings' => 'மேற்கோள் அமைப்புகள்',
        'number_prefix' => 'எண் முன்னொட்டு',
        'next_number' => 'அடுத்த எண்',
        'default_validity' => 'இயல்புநிலை செல்லுபடி (நாட்கள்)',
        'default_terms' => 'இயல்புநிலை விதிமுறைகள்',
        'change_password' => 'கடவுச்சொல்லை மாற்று',
        'current_password' => 'தற்போதைய கடவுச்சொல்',
        'new_password' => 'புதிய கடவுச்சொல்',
        'saved_successfully' => 'வெற்றிகரமாக சேமிக்கப்பட்டது.',
        'bill_customization' => 'பில் தனிப்பயனாக்கம்',
        'enable_header' => 'தலைப்பை இயக்கு (ஹெடர்)',
        'enable_footer' => 'அடிக்குறிப்பை இயக்கு (ஃபுட்டர்)',
        'font_style' => 'எழுத்துரு பாணி',
        'font_size' => 'எழுத்துரு அளவு',
        'theme_preset' => 'வடிவமைப்பு நிறம்',
        'theme_color' => 'முதன்மை நிறம்',
        'accent_color' => 'துணை நிறம்',
        'preset_classic' => 'கிளாசிக் நேவி',
        'preset_dark' => 'சார்கோல் டார்க்',
        'preset_green' => 'ஃபாரஸ்ட் கிரீன்',
        'preset_purple' => 'ராயல் பர்பிள்',
        'preset_red' => 'கிரிம்சன் ரெட்',
        'preset_custom' => 'விருப்ப நிறம்',
        'comparative_quotation' => 'ஒப்பீட்டு மேற்கோள்',
        'comparative_quotations' => 'ஒப்பீட்டு மேற்கோள்கள்',
        'option_group' => 'விருப்பம் குழு',
        'companies' => 'நிறுவனங்கள்',
        'add_company' => 'நிறுவனம் சேர்',
        'back_to_list' => 'பட்டியலுக்குத் திரும்பு',
    ],
];

function t(string $key, string $lang = 'en'): string
{
    if (!in_array($lang, ['en', 'ta'], true)) $lang = 'en';
    return $GLOBALS['LANG'][$lang][$key] ?? ($GLOBALS['LANG']['en'][$key] ?? $key);
}

/** Current UI language: query param > session > settings default > en */
function current_lang(): string
{
    if (isset($_GET['lang']) && in_array($_GET['lang'], ['en', 'ta'], true)) {
        $_SESSION['ui_lang'] = $_GET['lang'];
    }
    return $_SESSION['ui_lang'] ?? 'en';
}
